/* 

OPERADORES LÓGICOS:

&& -> AND que em português = E      // TODAS AS EXPRESSÕES PRECISAM SER VERDADEIRAS PARA RETORNAR TRUE
|| -> OR que em português = OU      // APENAS UMA EXPRESSÃO PRECISA SER VERDADEIRA PARA RETORNAR TRUE
!  -> NOT que em português = NÃO    // ELA INVERTE UMA EXPRESSÃO OU NEGA UMA EXPRESSÃO // FALSE PARA A SER TRUE e TRUE PARA A SER FALSE

*/


